import type { Metadata } from "next";
import "./globals.css";

import { font } from '@/fonts/font';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} light`}
      >
        {children}
      </body>
    </html>
  );
}
